# Generated by Django 5.0.3 on 2024-03-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0002_lecture_parentfeedback_psychotherapist_teengerfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentfeedback',
            name='sammary',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teengerfeedback',
            name='sammary',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
