# Generated by Django 5.0.3 on 2024-03-20 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0003_parentfeedback_sammary_teengerfeedback_sammary'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentfeedback',
            name='Parents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ourapp.parents'),
        ),
        migrations.AddField(
            model_name='teengerfeedback',
            name='Teengers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ourapp.teengers'),
        ),
    ]
