# Generated by Django 5.0.3 on 2024-03-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0006_alter_teengerfeedback_teengers'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentfeedback',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='teengerfeedback',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
