# Generated by Django 5.0.3 on 2024-04-03 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0004_alter_profile_user'),
        ('ourapp', '0008_profile'),
    ]

    operations = [
    ]
